Repository mui-org/material-ui-pickers, pull requests merged in 2018-05, with the labels that each got.

#402 Bug - date fns max year
  lib/src/utils/date-fns-utils.js
Labels: bug, date-fns

#411 [#406] [typescript] Make utils prop of MuiPickersUtilsProvider typed …
  lib/__tests__/DatePicker/DatePickerWrapper.usage.tsx
  lib/package-lock.json
  lib/src/utils/MuiPickersUtilsProvider.d.ts
Labels: typescript

#350 Update date on blur
  lib/src/_shared/DateTextField.jsx
Labels: needs work
