Repository mui-org/material-ui-pickers, pull requests merged in 2020-04, with the labels that each got.

#1663 [docs] Fix Shortcat -> Shortcut typo
  docs/pages/guides/accessibility.mdx
Labels: PR: ready to ship, docs

#1668 [typescript] Reexport DateRangePickerProps
  lib/src/DateRangePicker/DateRangePicker.tsx
Labels: PR: ready to ship, typescript

#1696 Rename keyboardIcon => openPickerIcon
  docs/pages/demo/datepicker/AdvancedKeyboard.example.jsx
  docs/pages/demo/datetime-picker/CustomDateTimePicker.example.jsx
  docs/prop-types.json
  lib/src/TimePicker/TimePicker.tsx
  lib/src/_shared/KeyboardDateInput.tsx
  lib/src/_shared/PickerToolbar.tsx
  lib/src/_shared/PureDateInput.tsx
  lib/src/_shared/icons/CalendarIcon.tsx
Labels: breaking change

#1661 Improve input mask UX and a11y
  .vscode/launch.json
  docs/package.json
  docs/pages/demo/datepicker/index.mdx
  docs/pages/demo/daterangepicker/index.mdx
  docs/pages/demo/datetime-picker/index.mdx
  docs/pages/demo/timepicker/index.mdx
  docs/pages/localization/Date-fns.example.jsx
  docs/pages/localization/Moment.example.jsx
  docs/prop-types.json
  e2e/integration/DatePicker.spec.ts
  lib/jest.config.js
  lib/package.json
  lib/src/DateRangePicker/DateRangePickerInput.tsx
  lib/src/DateRangePicker/DateRangePickerView.tsx
  lib/src/__tests__/KeyboardDatePicker.test.tsx
  lib/src/__tests__/unit/text-field-helper.test.ts
  lib/src/_helpers/text-field-helper.ts
  lib/src/_shared/KeyboardDateInput.tsx
  lib/src/_shared/PureDateInput.tsx
  lib/src/_shared/hooks/usePickerState.ts
  package.json
  yarn.lock
Labels: enhancement

#1702 [CalendarView] Fix a bunch of regressions
  e2e/integration/KeyboardNavigation.spec.ts
  lib/src/__tests__/DateRangePicker.test.tsx
  lib/src/views/Calendar/CalendarHeader.tsx
  lib/src/views/Calendar/CalendarView.tsx
  lib/src/views/Calendar/Day.tsx
  lib/src/views/Calendar/YearSelection.tsx
  lib/src/views/Calendar/useCalendarState.tsx
  lib/src/wrappers/StaticWrapper.tsx
  lib/src/wrappers/WrapperVariantContext.tsx
Labels: bug 🐛
