Repository mui-org/material-ui-pickers, pull requests merged in 2020-06, with the labels that each got.

#1847 [Day] Accept font-family from typography
  lib/src/views/Calendar/Day.tsx
Labels: bug 🐛

#1848 Fix not selectable last year
  .circleci/config.yml
  .vscode/launch.json
  .vscode/tasks.json
  docs/pages/guides/FormikOurValidation.example.tsx
  docs/pages/guides/FormikValidationSchema.example.tsx
  docs/pages/localization/calendar-systems.mdx
  lib/jest.config.js
  lib/package.json
  lib/src/DateRangePicker/DateRangePickerView.tsx
  lib/src/__tests__/DatePicker.test.tsx
  lib/src/__tests__/DatePickerRoot.test.tsx
  lib/src/__tests__/DatePickerTestingLib.test.tsx
  lib/src/__tests__/DateTimePickerRoot.test.tsx
  lib/src/__tests__/DateTimePickerTestingLib.test.tsx
  lib/src/__tests__/setup.ts
  lib/src/__tests__/test-utils.tsx
  lib/src/__tests__/tsconfig.json
  lib/src/_helpers/date-utils.ts
  lib/src/constants/prop-types.ts
  lib/src/views/Calendar/YearSelection.tsx
  yarn.lock
Labels: bug 🐛

#1897 [core] yarn prettier
  docs/pages/demo/datepicker/index.mdx
  lib/jest.config.js
  lib/src/__tests__/DatePicker.test.tsx
  lib/src/_helpers/time-utils.ts
Labels: PR: ready to ship, core

#1893 [docs] Prepare Material-UI X
  docs/pages/demo/daterangepicker/index.mdx
Labels: PR: ready to ship, docs

#1884 [docs] Improve Responsiveness sections
  docs/pages/demo/datepicker/index.mdx
  docs/pages/demo/daterangepicker/index.mdx
  docs/pages/demo/datetime-picker/index.mdx
  docs/pages/demo/timepicker/index.mdx
Labels: PR: ready to ship, docs

#1896 [core] Remove dead dependency
  docs/package.json
  yarn.lock
Labels: PR: ready to ship, core

#1914 Add missing props for DateRangePickerToolbar
  lib/src/DateRangePicker/DateRangePickerView.tsx
Labels: PR: ready to ship

#1904 [docs] Fix DatePicker of 'Customization' section
  docs/pages/demo/datepicker/CustomDay.example.jsx
Labels: PR: ready to ship, docs

#1873 [typescript] Fix theme overrides type failing
  lib/src/typings/overrides.ts
Labels: PR: ready to ship, typescript

#1929 [core] Update .github to match main repo
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/1.bug.md
  .github/ISSUE_TEMPLATE/2.feature.md
  .github/ISSUE_TEMPLATE/3.material-design.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: ready to ship
