Repository mui-org/material-ui-pickers, pull requests merged in 2020-05, with the labels that each got.

#1770 Support "empty" value in pickers' UX
  .vscode/settings.json
  docs/pages/demo/datepicker/DatePickers.example.jsx
  docs/pages/demo/timepicker/TimePickers.example.jsx
  docs/pages/demo/timepicker/index.mdx
  docs/prop-types.json
  lib/.size-snapshot.json
  lib/src/DatePicker/DatePickerToolbar.tsx
  lib/src/DateRangePicker/DateRangePicker.tsx
  lib/src/DateTimePicker/DateTimePickerTabs.tsx
  lib/src/DateTimePicker/DateTimePickerToolbar.tsx
  lib/src/Picker/Picker.tsx
  lib/src/Picker/makePickerWithState.tsx
  lib/src/TimePicker/TimePickerToolbar.tsx
  lib/src/__tests__/DatePicker.test.tsx
  lib/src/__tests__/DateTimePicker.test.tsx
  lib/src/__tests__/TimePicker.test.tsx
  lib/src/_helpers/date-utils.ts
  lib/src/_helpers/time-utils.ts
  lib/src/_shared/hooks/usePickerState.ts
  lib/src/typings/BasePicker.tsx
  lib/src/views/Calendar/Calendar.tsx
  lib/src/views/Calendar/CalendarView.tsx
  lib/src/views/Calendar/YearSelection.tsx
  lib/src/views/Calendar/useCalendarState.tsx
  lib/src/views/Clock/Clock.tsx
  lib/src/views/Clock/ClockNumbers.tsx
  lib/src/views/Clock/ClockView.tsx
  lib/src/wrappers/makeWrapperComponent.tsx
Labels: breaking change

#1773 Implement text props name convention
  docs/pages/demo/datetime-picker/CustomDateTimePicker.example.jsx
  docs/pages/demo/timepicker/TimePickers.example.jsx
  docs/pages/guides/Formats.example.jsx
  docs/pages/localization/Hijri.example.jsx
  docs/pages/localization/Persian.example.jsx
  docs/prop-types.json
  lib/.size-snapshot.json
  lib/src/__tests__/DatePickerProps.test.tsx
  lib/src/__tests__/shallow/ModalDialog.test.tsx
  lib/src/_shared/PickerModalDialog.tsx
  lib/src/typings/overrides.ts
  lib/src/views/Calendar/Calendar.tsx
  lib/src/views/Clock/ClockNumber.tsx
  lib/src/wrappers/MobileWrapper.tsx
  lib/src/wrappers/ResponsiveWrapper.tsx
  lib/src/wrappers/makeWrapperComponent.tsx
Labels: breaking change

#1804 [test] Make sure the components can render with a default theme
  lib/src/__tests__/DateTimePicker.test.tsx
  lib/src/__tests__/test-utils.tsx
Labels: PR: ready to ship

#1802 [core] Small changes
  docs/prop-types.json
  lib/src/DateTimePicker/DateTimePicker.tsx
  lib/src/DateTimePicker/DateTimePickerToolbar.tsx
  lib/src/Picker/Picker.tsx
  lib/src/Picker/SharedPickerProps.tsx
  lib/src/Picker/makePickerWithState.tsx
  lib/src/__tests__/DatePicker.test.tsx
  lib/src/__tests__/DateRangePicker.test.tsx
  lib/src/__tests__/DateTimePicker.test.tsx
  lib/src/__tests__/Theme.test.tsx
  lib/src/__tests__/TimePicker.test.tsx
  lib/src/__tests__/Validation.test.tsx
  lib/src/__tests__/unit/text-field-helper.test.ts
  lib/src/_helpers/date-utils.ts
  lib/src/_helpers/time-utils.ts
  lib/src/_helpers/utils.ts
  lib/src/_shared/ArrowSwitcher.tsx
  lib/src/_shared/KeyboardDateInput.tsx
  lib/src/_shared/PickerModalDialog.tsx
  lib/src/_shared/PickerToolbar.tsx
  lib/src/_shared/PureDateInput.tsx
  lib/src/_shared/ToolbarButton.tsx
  lib/src/_shared/ToolbarText.tsx
  lib/src/typings/BasePicker.tsx
  lib/src/views/Calendar/Calendar.tsx
  lib/src/views/Calendar/CalendarHeader.tsx
  lib/src/views/Calendar/CalendarView.tsx
  lib/src/views/Calendar/Day.tsx
  lib/src/views/Calendar/FadeTransitionGroup.tsx
  lib/src/views/Calendar/YearSelection.tsx
  lib/src/views/Clock/ClockView.tsx
  lib/src/wrappers/DesktopPopperWrapper.tsx
  lib/src/wrappers/DesktopWrapper.tsx
  lib/src/wrappers/ResponsiveWrapper.tsx
  lib/src/wrappers/makeWrapperComponent.tsx
  package.json
Labels: PR: ready to ship

#1816 [docs] improve English, move moment.js last due to bundle size
  docs/pages/getting-started/installation.mdx
Labels: PR: ready to ship

#1797 Fix ternary condition for default mask values
  lib/src/DateTimePicker/DateTimePicker.tsx
  lib/src/TimePicker/TimePicker.tsx
  lib/src/__tests__/DateTimePicker.test.tsx
  lib/src/__tests__/createClientRender.tsx
  package.json
  yarn.lock
Labels: PR: ready to ship, bug 🐛

#1831 [docs] Update parsing.mdx to use day.js document website
  docs/pages/getting-started/parsing.mdx
Labels: docs

#1815 [docs] Improve English and fix 404 link
  docs/pages/demo/datepicker/index.mdx
  docs/pages/demo/daterangepicker/index.mdx
  docs/pages/demo/datetime-picker/index.mdx
  docs/pages/demo/timepicker/index.mdx
  docs/pages/guides/static-components.mdx
Labels: docs

#1838 [docs] Remove outdated paragraph
  docs/pages/api/props.tsx
Labels: docs
